spring.application.name=price_alert
# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/yuvraj
spring.datasource.username=yuvraj
spring.datasource.password=yuv@postgres
spring.jpa.hibernate.ddl-auto=update

# Redis configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092

#binance api
binance.api.url=https://api.binance.com